# Generated by Django 4.2.7 on 2026-04-24 14:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('precio_adicional', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Géneros',
            },
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('sinopsis', models.TextField()),
                ('duracion', models.IntegerField(help_text='Duración en minutos')),
                ('clasificacion', models.CharField(choices=[('ATP', 'Todo Público'), ('+13', '+13'), ('+16', '+16'), ('+18', '+18')], max_length=3)),
                ('director', models.CharField(max_length=100)),
                ('actores_principales', models.TextField(help_text='Separar por comas')),
                ('fecha_estreno', models.DateField()),
                ('fecha_fin_cartelera', models.DateField(blank=True, null=True)),
                ('poster', models.ImageField(upload_to='posters/')),
                ('trailer_url', models.URLField(blank=True, help_text='URL del trailer de YouTube')),
                ('estado', models.CharField(choices=[('prox_estreno', 'Próximo Estreno'), ('cartelera', 'En Cartelera'), ('finalizada', 'Finalizada')], default='prox_estreno', max_length=20)),
                ('idioma_original', models.CharField(default='Español', max_length=50)),
                ('subtitulos', models.BooleanField(default=True)),
                ('doblada', models.BooleanField(default=True)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comentario', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('pelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peliculas.pelicula')),
            ],
        ),
    ]
