# Generated by Django 4.2.7 on 2026-04-24 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('peliculas', '0002_initial'),
        ('reservas', '0001_initial'),
        ('pagos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='reserva',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reservas.reserva'),
        ),
        migrations.AddField(
            model_name='cupondescuento',
            name='peliculas_aplicables',
            field=models.ManyToManyField(blank=True, to='peliculas.pelicula'),
        ),
    ]
