# Generated by Django 4.2.7 on 2026-04-24 14:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoSala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField()),
                ('precio_multiplicador', models.DecimalField(decimal_places=2, default=1.0, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('capacidad_total', models.IntegerField()),
                ('filas', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(26)])),
                ('asientos_por_fila', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('activa', models.BooleanField(default=True)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='salas.tiposala')),
            ],
        ),
        migrations.CreateModel(
            name='Asiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fila', models.CharField(max_length=1)),
                ('numero', models.IntegerField()),
                ('tipo', models.CharField(choices=[('regular', 'Regular'), ('preferente', 'Preferente'), ('vip', 'VIP'), ('pasillo', 'Pasillo')], default='regular', max_length=20)),
                ('discapacitado', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salas.sala')),
            ],
            options={
                'ordering': ['sala', 'fila', 'numero'],
                'unique_together': {('sala', 'fila', 'numero')},
            },
        ),
    ]
