# Generated by Django 4.2.7 on 2026-04-24 14:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('peliculas', '0002_initial'),
        ('salas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=8)),
                ('activa', models.BooleanField(default=True)),
                ('formato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peliculas.formato')),
                ('pelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peliculas.pelicula')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salas.sala')),
            ],
        ),
        migrations.CreateModel(
            name='TipoEntrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('precio_multiplicador', models.DecimalField(decimal_places=2, default=1.0, max_digits=3)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('codigo', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asientos', models.CharField(max_length=200)),
                ('cantidad_entradas', models.IntegerField()),
                ('precio_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('temporal', 'Temporal'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada'), ('expirada', 'Expirada')], default='temporal', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_expiracion', models.DateTimeField()),
                ('fecha_confirmacion', models.DateTimeField(blank=True, null=True)),
                ('funcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.funcion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BloqueoAsiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_bloqueo', models.DateTimeField(auto_now_add=True)),
                ('fecha_expiracion', models.DateTimeField()),
                ('sesion_id', models.CharField(max_length=100)),
                ('asiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salas.asiento')),
                ('funcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.funcion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
